Example/HCaptcha.xcodeproj/project.pbxproj, Example/HCaptcha_Tests/Core/HCaptchaWebViewManager__HTML__Tests.swift, Example/HCaptcha_Tests/Helpers/HCaptchaConfig+Helpers.swift, Example/HCaptcha_Tests/Helpers/HCaptchaWebViewManager+Helpers.swift, HCaptcha/Assets/hcaptcha.html, HCaptcha/Classes/HCaptcha.swift, HCaptcha/Classes/HCaptchaWebViewManager.swift, README.md
Captcha size can be configured
=> Add size modes

HCaptcha/Assets/hcaptcha.html, HCaptcha/Classes/HCaptchaWebViewManager.swift
Fixed checkbox alignment — now it's centered both vertically and horizontally, instead of being pinned to the top-left corner.
Both new CSS and new JS-code is taken directly from android-sdk.
Also, captcha can be closed if tapped outside of it.
=> Checkbox alignment and captcha dismiss

.github/workflows/workflow.yml, .gitignore, Package.swift, README.md, fastlane/Fastfile
=> #5 add Swift Package Manager configuration

CHANGELOG.md, Example/HCaptcha_Tests/Core/HCaptchaWebViewManager__HTML__Tests.swift, Example/Podfile.lock, HCaptcha.podspec, MAINTAINERS.md, README.md, fastlane/Fastfile
=> Bump to 1.7.0

.jshintrc, CHANGELOG.md, Example/HCaptcha.xcodeproj/project.pbxproj, Example/HCaptcha/Base.lproj/Main.storyboard, Example/HCaptcha/ViewController.swift, Example/HCaptcha_Tests/Core/HCaptchaDecoder__Tests.swift, Example/HCaptcha_Tests/Core/HCaptchaWebViewManager__Tests.swift, Example/HCaptcha_Tests/Helpers/HCaptchaError+Equatable.swift, Example/HCaptcha_Tests/mock.html, Example/Podfile.lock, HCaptcha-Carthage.xcodeproj/project.pbxproj, HCaptcha.podspec, HCaptcha/Assets/hcaptcha.html, HCaptcha/Classes/HCaptchaDebugInfo.swift, HCaptcha/Classes/HCaptchaDecoder.swift, HCaptcha/Classes/HCaptchaError.swift, HCaptcha/Classes/HCaptchaWebViewManager.swift, package.json, yarn.lock
=> Bugfix/jshint upgrade + error code consistency

Example/ObjC/ViewController.m
=> Update ObjC example to properly close WebView

Example/HCaptcha_Tests/Core/HCaptchaWebViewManager__HTML__Tests.swift, README.md
=> #46 update README documentation about WebView hide responsibility

HCaptcha/Classes/HCaptchaDebugInfo.swift
=> #49 Fix 'nil while unwrapping an Optional value' on URL construction

CHANGELOG.md, Example/Podfile.lock, HCaptcha.podspec
=> Bump to 2.2.0

.gitignore, .swiftlint.yml, README.md, fastlane/Fastfile
- #79
No issues were observed during the analysis
Also, I found one more tool for SPM https://github.com/marinofelipe/swift-package-info, but to be honest I'm not sure that we need it
=> #79 add pod_size lane to check size impact on application binary

CHANGELOG.md, Example/Podfile.lock, HCaptcha.podspec, HCaptcha/Assets/hcaptcha.html, README.md
Similar fix as we did for Android https://github.com/hCaptcha/hcaptcha-android-sdk/pull/50
=> Fix double challengeClosed error reporting

.github/workflows/workflow.yml
=> chore(ci): move out of ::set-output command (#105)

CHANGELOG.md, Example/HCaptcha_Tests/Core/HCaptchaWebViewManager__HTML__Tests.swift, Example/HCaptcha_Tests/Helpers/HCaptchaConfig+Helpers.swift, Example/HCaptcha_Tests/Helpers/HCaptchaWebViewManager+Helpers.swift, Example/Podfile.lock, HCaptcha.podspec, HCaptcha/Assets/hcaptcha.html, HCaptcha/Classes/HCaptcha.swift, HCaptcha/Classes/HCaptchaConfig.swift, HCaptcha/Classes/HCaptchaHtml.swift, HCaptcha/Classes/HCaptchaWebViewManager.swift
Related PR https://github.com/hCaptcha/hcaptcha-android-sdk/pull/103
=> Add orientation argument to HCaptcha.init

HCaptcha/Classes/HCaptchaLog.swift, MAINTAINERS.md
=> fix(sdk): reduce logging from release build

Example/HCaptcha/ViewController.swift, Example/HCaptcha_Tests/Core/HCaptcha__Tests.swift, HCaptcha/Classes/HCaptcha.swift, README.md
Based on https://github.com/hCaptcha/HCaptcha-ios-sdk/pull/139
=> feat: HCaptcha.redrawView

CHANGELOG.md, Example/Podfile.lock, HCaptcha-Carthage.xcodeproj/project.pbxproj, HCaptcha.podspec, HCaptcha/Resources/PrivacyInfo.xcprivacy, Package.swift, fastlane/Fastfile
=> feat: add PrivacyInfo.xcprivacy #128

.github/workflows/workflow.yml
Similar to changes that was done for `react-native-hcaptcha`
=> ci: do pod push ofter release created

CHANGELOG.md, Example/HCaptcha_Tests/Core/HCaptchaResult__Tests.swift, Example/HCaptcha_Tests/Core/HCaptchaWebViewManager__Tests.swift, Example/Podfile.lock, HCaptcha-Carthage.xcodeproj/project.pbxproj, HCaptcha.podspec, HCaptcha/Classes/HCaptchaResult.swift, HCaptcha/Classes/HCaptchaWebViewManager+WKNavigationDelegate.swift, HCaptcha/Classes/HCaptchaWebViewManager.swift
=> feat: don't emit sessionTimeout once result.dematerialize is called

.github/workflows/workflow.yml, Example/HCaptcha.xcodeproj/xcshareddata/xcschemes/HCaptcha-Example.xcscheme, Example/HCaptcha_Tests/Core/HCaptchaWebViewManager__HTML__Tests.swift, Example/HCaptcha_Tests/Core/HCaptchaWebViewManager__Tests.swift, Example/HCaptcha_Tests/Core/HCaptcha__Bench.swift, Example/HCaptcha_Tests/Core/HCaptcha__Config__Tests.swift, Example/HCaptcha_Tests/Core/HCaptcha__Tests.swift, Example/HCaptcha_Tests/Helpers/HCaptchaConfig+Helpers.swift, Example/HCaptcha_Tests/Helpers/HCaptchaWebViewManager+Helpers.swift, HCaptcha/Classes/HCaptcha.swift, HCaptcha/Classes/HCaptchaConfig.swift, HCaptcha/Classes/HCaptchaWebViewManager.swift, fastlane/Fastfile
=> feat: passive site key

README.md
=> docs: added " Token expiration" section to README.md
